import user1 from "../assets/photos/user1.webp";
import user2 from "../assets/photos/user2.webp";
import user3 from "../assets/photos/user3.webp";
import user4 from "../assets/photos/user4.webp";
import user5 from "../assets/photos/user5.webp";

export const REVIEWS = [
  {
    id: 1,
    name: "Lars Svensson",
    role: "Inversor Sueco",
    body: "La gestión de Terral Studio en mi propiedad de Marbella fue impecable. Entienden el lujo mediterráneo y logran un equilibrio perfecto.",
    img: user5,
  },
  {
    id: 2,
    name: "Carmen Heredia",
    role: "Propietaria",
    body: "No es solo arquitectura, es cómo capturan la luz de Málaga en cada rincón. Transformaron mi vivienda en algo mágico.",
    img: user2,
  },
  {
    id: 3,
    name: "Michael Chen",
    role: "Inversor Internacional",
    body: "El equipo de Terral Studio demostró un nivel de profesionalidad increíble. El proyecto se completó a tiempo y superó nuestras expectativas.",
    img: user3,
  },
  {
    id: 4,
    name: "Elena Góngora",
    role: "Promotora Inmobiliaria",
    body: "Colaborar con ellos ha sido un acierto total. Su visión contemporánea y el respeto por el entorno hacen que cada villa sea única e irrepetible.",
    img: user4,
  },
  {
    id: 5,
    name: "Thomas Müller",
    role: "Residente en la Costa del Sol",
    body: "Desde el diseño inicial hasta la entrega de llaves, el proceso fue muy claro. Han creado la casa de nuestros sueños sin retrasos.",
    img: user5,
  },
  {
    id: 6,
    name: "Sofía Valenzuela",
    role: "Interiorista",
    body: "Trabajar codo con codo con su equipo de arquitectos es una delicia. Tienen una sensibilidad espacial exquisita de principio a fin.",
    img: user1,
  },
  {
    id: 7,
    name: "James y Sarah Wright",
    role: "Expatriados Británicos",
    body: "Gracias a Terral Studio nuestra transición a la vida en España ha sido mucho más fácil. Su servicio integral de edificación es modélico.",
    img: user2,
  },
  {
    id: 8,
    name: "Alejandro Ruiz",
    role: "Empresario",
    body: "El rediseño de nuestras oficinas corporativas no solo superó nuestras expectativas sino que aumentó notablemente la moral del equipo.",
    img: user3,
  },
  {
    id: 9,
    name: "Verónica López",
    role: "Propietaria",
    body: "Increíble la calidad de los materiales y acabados elegidos. Cada textura tiene un sentido dentro del espacio arquitectónico propuesto.",
    img: user4,
  },
  {
    id: 10,
    name: "Jean-Pierre Blanc",
    role: "Inversor Francés",
    body: "Rentabilidad asegurada gracias a su excelente asesoramiento para conseguir los mejores terrenos y diseños de alta demanda en Marbella.",
    img: user5,
  },
  {
    id: 11,
    name: "Marta Domínguez",
    role: "Directora de Hotel",
    body: "La reforma del lobby del hotel ha sido un éxito unánime y a los clientes les encanta la nueva atmósfera elegante que han conseguido.",
    img: user1,
  },
  {
    id: 12,
    name: "David y Emma Jones",
    role: "Propietarios",
    body: "Nos acompañaron atentamente durante toda la construcción de nuestra villa en Estepona. La atención fue totalmente personalizada.",
    img: user2,
  },
  {
    id: 13,
    name: "Ignacio Ferrer",
    role: "Arquitecto Asociado",
    body: "La innovación conceptual y el desarrollo riguroso de cada plano en Terral Studio los sitúa como referentes en la Costa del Sol.",
    img: user3,
  },
  {
    id: 14,
    name: "Marina Castaño",
    role: "Emprendedora",
    body: "Rediseñaron mi boutique captando la verdadera esencia de mi marca de ropa. Los clientes pasan más tiempo gracias a la fluidez del espacio.",
    img: user4,
  },
  {
    id: 15,
    name: "Oliver Smith",
    role: "Inversor Privado",
    body: "Incluso gestionando la obra desde mi país, sentí confianza plena. Son comunicativos, resuelven los problemas técnicos y cuidan el detalle.",
    img: user5,
  },
  {
    id: 16,
    name: "Laura Jiménez",
    role: "Propietaria",
    body: "La cantidad de luz natural que consiguieron introducir en una casa que era oscura inicialmente me dejó boquiabierta. Magnífico trabajo.",
    img: user1,
  },
  {
    id: 17,
    name: "Carlos Medina",
    role: "Promotor Local",
    body: "Eficientes, resolutivos y enormemente creativos a la hora de maximizar parcelas complicadas. Seguiremos trabajando a largo plazo.",
    img: user2,
  },
  {
    id: 18,
    name: "Aisha Al-Fayed",
    role: "Propietaria",
    body: "Valoro muchísimo la exclusividad y la privacidad. Supieron concebir un diseño en el que nunca te sientes expuesto pero estás en pleno campo.",
    img: user3,
  },
  {
    id: 19,
    name: "Gonzalo Herrera",
    role: "Abogado",
    body: "Una arquitectura que respeta el entorno y dialoga con la naturaleza. Los espacios exteriores e interiores están perfectamente conectados.",
    img: user4,
  },
  {
    id: 20,
    name: "Jens Petersen",
    role: "Inversor Danés",
    body: "La aplicación de estándares de confort nórdico en el cálido clima mediterráneo. Es el equilibrio definitivo entre bienestar y buen diseño.",
    img: user5,
  },
];
